export const SET_SPAREPARTS_OFFSET_LIMIT = 'SET_SPAREPARTS_OFFSET_LIMIT';
export const FETCH_SPAREPARTS_START = 'FETCH_SPAREPARTS_START';
export const FETCH_SPAREPARTS_SUCCESS = 'FETCH_SPAREPARTS_SUCCESS';
export const FETCH_SPAREPARTS_FAIL = 'FETCH_SPAREPARTS_FAIL';
export const SET_SPAREPARTS_PAGE = 'SET_SPAREPARTS_PAGE';
export const UNMOUNT_SPAREPARTS = 'UNMOUNT_SPAREPARTS';